---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  vars:
     kubeconfig_path: kubeconfig
     oauth_identity_provider: oauth_identity_provider.yml
       
  tasks:
    - name: Create HTPasswd file
      shell: |
        htpasswd -c -B -b /tmp/htpasswd {{ username }} {{ password }}
      register: htpasswd_output
      vars:
        htpasswd_username: "testuser"  # Username for HTPasswd
        htpasswd_password: "testpass"  # Password for HTPasswd
      delegate_to: 10.76.107.101
    - name: create identity provider CR
      blockinfile:
        path: /tmp/oauth_identity_provider.yml
        create: true
        block: |
              apiVersion: config.openshift.io/v1
              kind: OAuth
              metadata:
                name: cluster
              spec:
                identityProviders:
                - name: htpasswd
                  mappingMethod: claim
                  type: HTPasswd
                  htpasswd:
                    fileData:
                      name: htpass-secret
      delegate_to: 10.76.107.101
    - name: login to ocp
      shell: | 
               oc login -u kubeadmin -p SCkff-wqao2-fbP2U-ScxS2 https://api.nareshp.lab.psi.pnq2.redhat.com:6443 --insecure-skip-tls-verify=true 
               oc create secret generic htpass-secret --from-file=htpasswd=/tmp/htpasswd -n openshift-config
               oc apply -f /tmp/oauth_identity_provider.yml
      delegate_to: 10.76.107.101
    - name: grant admin rights to user
      shell: oc adm policy add-role-to-user admin "{{ username }}" -n "{{ namespace }}"
      delegate_to: 10.76.107.101


