---
- hosts: localhost
  gather_facts: false
  vars:
    namespace: demo
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Create HTPasswd file
      shell: htpasswd -c -B -b /tmp/htpasswd {{ htpasswd_username }} {{ htpasswd_password }}
      register: htpasswd_output
      vars:
        htpasswd_username: "testuser"  # Username for HTPasswd
        htpasswd_password: "testpass"  # Password for HTPasswd

    - name: Create secret from HTPasswd file
      redhat.openshift.k8s:
        state: present
        kind: Secret
        name: htpass-secret
        namespace: openshift-config
        definition:
          apiVersion: v1
          data:
            htpasswd: "{{ lookup('file', '/tmp/htpasswd') | b64encode }}"
          type: Opaque

    - name: Configure OAuth identity provider
      redhat.openshift.k8s:
        state: present
        src: oauth_identity_provider.yml  # Path to your OAuth identity provider YAML file
        force: yes
