---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  tasks:
    - name: Create HTPasswd file
      shell: |
        htpasswd -c -B -b /tmp/htpasswd {{ htpasswd_username }} {{ htpasswd_password }}
      register: htpasswd_output
      vars:
        htpasswd_username: "testuser"  # Username for HTPasswd
        htpasswd_password: "testpass"  # Password for HTPasswd
      delegate_to: 10.76.107.101
    - name: login to ocp
      command: oc login -u kubeadmin -p SCkff-wqao2-fbP2U-ScxS2; oc create secret generic htpass-secret --from-file=htpasswd=/tmp/htpasswd -n openshift-config
      args:
        executable: /bin/bash
      delegate_to: 10.76.107.101
    - name: Create secret from HTPasswd file
      command: oc create secret generic htpass-secret --from-file=htpasswd=/tmp/htpasswd -n openshift-config
      args:
        executable: /bin/bash
      delegate_to: 10.76.107.101

    - name: Configure OAuth identity provider
      command: oc apply -f oauth_identity_provider.yaml
      args:
        executable: /bin/bash
      become: true
      become_user: "{{ openshift_username }}"
