---
- hosts: localhost
  gather_facts: false
 # collections:
  #  - community.general
  vars:
    namespace: demo
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Create HTPasswd file
      shell: |
        htpasswd -c -B -b /tmp/htpasswd {{ htpasswd_username }} {{ htpasswd_password }}
      register: htpasswd_output
      vars:
        htpasswd_username: "testuser"  # Username for HTPasswd
        htpasswd_password: "testpass"  # Password for HTPasswd
      delegate_to: 10.76.107.101

    - name: cat /tmp/htpasswd
      shell: ls -lrth /tmp/htpasswd ; cat /tmp/htpasswd
      delegate_to: 10.76.107.101
    - name: copy file
      copy:
        src: /tmp/htpasswd
        dest: /tmp/
        remote_src: yes
      delegate_to: 10.76.107.101
    - name:
      command: oc create secret generic htpass-secret --from-file=htpasswd=/tmp/htpasswd -n openshift-config
      args:
        executable: /bin/bash
      delegate_to: 10.76.107.101


    - name: Configure OAuth identity provider
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: oauth_identity_provider.yml  # Path to your OAuth identity provider YAML file
        force: yes
