---
- hosts: localhost
  gather_facts: false
 # collections:
  #  - community.general
  vars:
    namespace: demo
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Create HTPasswd file
      shell: |
        htpasswd -c -B -b /tmp/htpasswd {{ htpasswd_username }} {{ htpasswd_password }}
      register: htpasswd_output
      vars:
        htpasswd_username: "testuser"  # Username for HTPasswd
        htpasswd_password: "testpass"  # Password for HTPasswd
      delegate_to: 10.76.107.101
   # - name: Add a user to a password file and ensure permissions are set
    #  htpasswd:
     #   path: /tmp/htpasswd
     #   name: testuser
     #   password: 'testpass'
     #   owner: root
     #   group: root
     #   mode: 0640
    - name: cat /tmp/htpasswd
      shell: ls -lrth /tmp/htpasswd ; cat /tmp/htpasswd
      delegate_to: 10.76.107.101
    - name: copy file
      copy:
        src: /tmp/htpasswd
        dest: /tmp/
      delegate_to: 10.76.107.101
    
    - name: Create secret from HTPasswd file
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        kind: Secret
        name: htpass-secret
        namespace: openshift-config
        definition:
          apiVersion: v1
          data:
            htpasswd: "{{ lookup('file', '/tmp/htpasswd') | b64encode }}"
          type: Opaque


    - name: Configure OAuth identity provider
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: oauth_identity_provider.yml  # Path to your OAuth identity provider YAML file
        force: yes
