---
- hosts: localhost
  gather_facts: false
  vars:
    namespace: test
    kubeconfig_path: kubeconfig 
    resource_limits_cpu: 1
    resource_limits_memory: 1
    resource_requests_cpu: 1
    resource_requests_memory: 1  
  tasks:
    - name: Set Quota Limits and Requests
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ namespace }}"
        state: present
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: compute-quota
          spec:
            hard:
              - limits
                 - cpu: "{{ resource_limits_cpu }}"
                 - memory: "{{ resource_limits_memory }}"
              - requests
                  - cpu: "{{ resource_requests_cpu }}"
                  - memory: "{{ resource_requests_memory }}"
      #delegate_to: localhost
