---
- hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Allow traffic from ingress
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: NetworkPolicy
          apiVersion: v1
          metadata:
            name: allow-from-openshift-ingress
            namespace: "{{ project_name }}"
          spec:
            podSelector:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: ingress
            podSelector: {}
            policyTypes:
            - Ingress
      when : >-
        "allow_from_openshift_ingress in net_pol"
