---
- hosts: localhost
  gather_facts: false
  vars:
    namespace: test
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Deny all traffic from outside by default
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: NetworkPolicy
          apiVersion: v1
          metadata:
            name: allow-from-openshift-ingress
            namespace: "{{ namespace }}"
          spec:
            podSelector:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: ingress
            podSelector: {}
            policyTypes:
            - Ingress
      when : allow_from_same_namespace in "{{ net_pol }}"
