---
- hosts: localhost
  gather_facts: false
  vars:
    namespace: demo
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Deny all traffic from openshift monitoring
      redhat.openshift.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: NetworkPolicy
          apiVersion: v1
          metadata:
            name: allow-from-openshift-monitoring
            namespace: demo
          spec:
            podSelector:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: monitoring
            podSelector: {}
            policyTypes:
            - Ingress
