---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  vars:
     kubeconfig_path: kubeconfig
     oauth_identity_provider: oauth_identity_provider.yml
       
  tasks:
  - name: reject Approval
    shell: "Request Rejected"
    register: out
