---
- name: Check request status
  hosts: localhost
  tasks:
  - name: Check status of request
    shell: echo "{{ request }}"
    register: out
  - name: Approve Request
    shell: echo "Request Rejected"
    register: approved
    when: >
      "NO" in out.stdout
    delegate_to: 10.76.107.101
  - name: Print Request Status
    debug:
      msg: "{{ approved.stdout }}"
    when: >
      "No" in out.stdout
  
