---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  vars:
     kubeconfig_path: kubeconfig
     oauth_identity_provider: oauth_identity_provider.yml
       
  tasks:
  - name: reject Approval
    shell: echo "Request Rejected"
    register: out
    delegate_to: 10.76.107.101
  - name: Request Status
    debug:
      msg: "{{ out.stdout }}"
  
