---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  tasks:
    - name: grant admin rights to user
      shell: |
             oc login -u kubeadmin -p SCkff-wqao2-fbP2U-ScxS2 https://api.nareshp.lab.psi.pnq2.redhat.com:6443 --insecure-skip-tls-verify=true
             oc adm policy add-role-to-user admin "{{ username }}" -n "{{ project_name }}"
      delegate_to: 10.76.107.101
  
