---
- name: Configure HTPasswd identity provider in OpenShift
  hosts: localhost
  vars:
     kubeconfig_path: kubeconfig
     oauth_identity_provider: oauth_identity_provider.yml
       
  tasks:
  - name: Check status of request
    debug: 
      msg: "{{ request }}"
    register: out
  - name: Approve Request
    shell: echo "Request Approved"
    register: approved
    delegate_to: 10.76.107.101


