---
- name: Compare Current Time with Provided Time
  hosts: localhost
  gather_facts: yes
  vars:
    provided_time: "2024-06-03T12:34:56Z"  # example provided time in ISO 8601 format
  tasks:
    - name: Get the current time in ISO 8601 format
      set_fact:
        current_time: "{{ ansible_date_time.iso8601 }}"

    - name: Convert provided time and current time to datetime objects
      set_fact:
        provided_time_obj: "{{ provided_time | to_datetime }}"
        current_time_obj: "{{ current_time | to_datetime }}"

    - name: Compare the times
      set_fact:
        is_after: "{{ current_time_obj > provided_time_obj }}"
        is_before: "{{ current_time_obj < provided_time_obj }}"
        is_equal: "{{ current_time_obj == provided_time_obj }}"

    - name: Print the current time and provided time
      debug:
        msg:
          - "Current Time: {{ current_time }}"
          - "Provided Time: {{ provided_time }}"

    - name: Print comparison result
      debug:
        msg: >-
          {% if is_after %}
            Current time is after the provided time.
          {% elif is_before %}
            Current time is before the provided time.
          {% elif is_equal %}
            Current time is equal to the provided time.
          {% else %}
            Error in comparison.
          {% endif %}
